global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'sleek-health-monitor'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter-singapore'
    ec2_sd_configs:
      - region: ap-southeast-1
        port: 9100
        filters:
          - name: tag:Project
            values: [sleek-hm]
          - name: tag:Environment
            values: [singapore]
          - name: instance-state-name
            values: [running]
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance_name
      - source_labels: [__meta_ec2_tag_Environment]
        target_label: environment
      - source_labels: [__meta_ec2_availability_zone]
        target_label: availability_zone
      - source_labels: [__meta_ec2_instance_type]
        target_label: instance_type

  - job_name: 'node-exporter-hongkong'
    ec2_sd_configs:
      - region: ap-northeast-1
        port: 9100
        filters:
          - name: tag:Project
            values: [sleek-hm]
          - name: tag:Environment
            values: [hongkong]
          - name: instance-state-name
            values: [running]
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance_name
      - source_labels: [__meta_ec2_tag_Environment]
        target_label: environment
      - source_labels: [__meta_ec2_availability_zone]
        target_label: availability_zone
      - source_labels: [__meta_ec2_instance_type]
        target_label: instance_type

  - job_name: 'node-exporter-australia'
    ec2_sd_configs:
      - region: ap-southeast-2
        port: 9100
        filters:
          - name: tag:Project
            values: [sleek-hm]
          - name: tag:Environment
            values: [australia]
          - name: instance-state-name
            values: [running]
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance_name
      - source_labels: [__meta_ec2_tag_Environment]
        target_label: environment
      - source_labels: [__meta_ec2_availability_zone]
        target_label: availability_zone
      - source_labels: [__meta_ec2_instance_type]
        target_label: instance_type

  - job_name: 'node-exporter-uk'
    ec2_sd_configs:
      - region: eu-west-2
        port: 9100
        filters:
          - name: tag:Project
            values: [sleek-hm]
          - name: tag:Environment
            values: [uk]
          - name: instance-state-name
            values: [running]
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance_name
      - source_labels: [__meta_ec2_tag_Environment]
        target_label: environment
      - source_labels: [__meta_ec2_availability_zone]
        target_label: availability_zone
      - source_labels: [__meta_ec2_instance_type]
        target_label: instance_type

  - job_name: 'blackbox-http-singapore'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://sleek-hm-alb-sin-1105181195.ap-southeast-1.elb.amazonaws.com/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
      - target_label: region
        replacement: singapore

  - job_name: 'blackbox-http-hongkong'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://sleek-hm-alb-hon-1310035724.ap-northeast-1.elb.amazonaws.com/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
      - target_label: region
        replacement: hongkong

  - job_name: 'blackbox-http-australia'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://sleek-hm-alb-aus-103235968.ap-southeast-2.elb.amazonaws.com/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
      - target_label: region
        replacement: australia

  - job_name: 'blackbox-http-uk'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://sleek-hm-alb-uk-503336061.eu-west-2.elb.amazonaws.com/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
      - target_label: region
        replacement: uk

  - job_name: 'sleek-application-metrics'
    scrape_interval: 30s
    static_configs:
      - targets:
        - sleek-hm-alb-sin-1105181195.ap-southeast-1.elb.amazonaws.com:80
        - sleek-hm-alb-hon-1310035724.ap-northeast-1.elb.amazonaws.com:80
        - sleek-hm-alb-aus-103235968.ap-southeast-2.elb.amazonaws.com:80
        - sleek-hm-alb-uk-503336061.eu-west-2.elb.amazonaws.com:80
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        regex: '([^:]+):.*'
        target_label: region
        replacement: '${1}'